export {
  ApiPath,
  AuthApiPath,
  MastersApiPath,
  TenantsApiPath,
  EAMApiPath,
  GroupsApiPath,
  WorkersApiPath,
  BSApiPath,
  SCApiPath,
  SLCApiPath,
  SLCFunctionApiPath,
  SpacesApiPath,
  InstancesApiPath,
  SshKeysApiPath,
  ObjectsApiPath,
} from 'bws-shared/common/enums/enums';
