export * as auth from './auth/actions';
export * as app from './app/actions';
export * as EAMGroupConfigurate from './eam-group-configurate/actions';
export * as eam from './eam/actions';
export * as bs from './bs/actions';
export * as BSSpace from './bs-space-create/actions';
export * as EAMWorkerConfigurate from './eam-worker-configurate/actions';
export * as SCConfigurateInstance from './sc-configurate-instance/actions';
export * as SLCFunctionConfigurate from './slc-configurate-function/actions';
