version: '3.8'

services:
  xs_bot_postgres:
    container_name: xs_bot_postgres
    image: postgres:14.1
    restart: on-failure
    ports:
      - 5432:5432
    networks:
      - xs_bot_backend_network
    env_file:
      - ../../.env/postgres.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=xs_bot
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - db_volume:/var/lib/postgresql/data
      - ./postgresql/dumps:/dumps

volumes:
  db_volume:
    external: true

networks:
  xs_bot_backend_network:
    driver: bridge
