version: "3.8"

services:
  bws_postgres:
    container_name: bws_postgres
    image: postgres:14.1
    restart: on-failure
    ports:
      - 7433:5432
    networks:
      - bws_backend_network
    env_file:
      - ../../.env/postgres.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bws
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - bws_postgres_data:/var/lib/postgresql/data

  bws_backend:
    container_name: bws_backend
    depends_on:
      - bws_postgres
    build:
      context: ../../
      dockerfile: backend/Dockerfile.local
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        npm run migrate:dev
        npm run start:prod
    ports:
      - 3001:3001
    env_file:
      - ../../.env/backend.env
    environment:
      - DB_USER=postgres
      - DB_DATABASE=bws
      - DB_HOST=bws_postgres
      - DB_PORT=5432
      - FRONTEND_URL=http://bws_frontend:80
    networks:
      - bws_backend_network
      - bws_frontend_network

  bws_frontend:
    container_name: bws_frontend
    build:
      context: ../../
      dockerfile: frontend/Dockerfile.local
      args:
        NGINX_CONFIG_NAME: nginx.local.conf
        REACT_APP_API_ORIGIN_URL: /api/v1
    restart: on-failure
    ports:
      - 3000:80
    networks:
      - bws_backend_network
      - bws_frontend_network

volumes:
  bws_postgres_data:
    driver: local

networks:
  bws_backend_network:
    driver: bridge
  bws_frontend_network:
    driver: bridge
