version: "3.8"

services:
  bws_postgres:
    container_name: bws_postgres
    image: postgres:14.1
    restart: on-failure
    ports:
      - 7433:5432
    networks:
      - bws_backend_network
    env_file:
      - ../../.env/postgres.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=bws
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - bws_postgres_data:/var/lib/postgresql/data

  bws_backend:
    container_name: bws_backend
    image: docker.pkg.github.com/binarystudioacademy/bsa-winter-2021-2022-bws/bws-backend-development:latest
    depends_on:
      - bws_postgres
    restart: on-failure
    command:
      - /bin/sh
      - -c
      - |
        npm run migrate:dev
        npm run start:prod
    ports:
      - 3001:3001
    networks:
      - bws_backend_network
      - bws_frontend_network
    env_file:
      - ../../.env/backend.env
    environment:
      - DB_USER=postgres
      - DB_DATABASE=bws
      - DB_HOST=bws_postgres
      - DB_PORT=5432
      - FRONTEND_URL=http://bws_frontend:80

  bws_frontend:
    container_name: bws_frontend
    image: docker.pkg.github.com/binarystudioacademy/bsa-winter-2021-2022-bws/bws-frontend-development:latest
    depends_on:
      - bws_backend
    restart: on-failure
    ports:
      - 3000:80
    networks:
      - bws_backend_network
      - bws_frontend_network

  bws_frontend_auto_ssl:
    image: valian/docker-nginx-auto-ssl
    depends_on:
      - bws_frontend
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    networks:
      - bws_backend_network
      - bws_frontend_network
    volumes:
      - bws_frontend_auto_ssl_data:/etc/resty-auto-ssl
      - ./:/etc/nginx/conf.d
    environment:
      ALLOWED_DOMAINS: 'development.bws-cloud.com'
      SITES: 'development.bws-cloud.com=bws_frontend:80'

volumes:
  bws_postgres_data:
    driver: local
  bws_frontend_auto_ssl_data:
    driver: local

networks:
  bws_backend_network:
    driver: bridge
  bws_frontend_network:
    driver: bridge
