export {
  START_TEXT,
  FOREX_TEXT,
  FAQ_TEXT,
  PERSONAL_AREA_TEXT,
  CRYPTO_TEXT,
  CRYPTO_BUTTON_TEXT,
  SCRILL_TEXT,
  SWIFT_TEXT,
  BANK_CARD_TEXT,
  CONFIRM_PAYMENT_TEXT,
} from './text.enum';

export {
  FOREX_TITLE,
  FAQ_TITLE,
  FAQ_BUTTON_TITLE,
  PERSONAL_AREA_TITLE,
  PERSONAL_AREA_BUTTON_TITLE,
  CRYPTO_TITLE,
  CRYPTO_BUTTON_TITLE,
  SCRILL_TITLE,
  SWIFT_TITLE,
  BANK_CARD_TITLE,
  CONFIRM_PAYMENT_TITLE,
  BACK,
} from './title.enum';
